spring:
  application:
    name: springgradle
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    password: 1
    dbcp:
      max-wait: 5
  jpa:
    show-sql: true
logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
      hibernate: error
  file: ${spring.application.name}.log
