spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    password: 1
    dbcp:
      max-wait: 5
  jpa:
    show-sql: true
